version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=airflow_users
      - POSTGRES_PASSWORD=airflow_pass
      - POSTGRES_DB=airflow_db
    ports:
      - "5432:5432"

  first_airflow:
    image: first_airflow:latest
    depends_on: 
      - postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow_users:airflow_pass@postgres/airflow_db
      - JAVA_HOME=/opt/java  # Ensure this matches the JAVA_HOME in the Dockerfile
      - HADOOP_HOME=/opt/hadoop  # Ensure this matches the HADOOP_HOME in the Dockerfile
    volumes:
      - ./airflow:/opt/airflow
      - /c/lib/jdk8u402-b06:/opt/java  # Corrected path to match the host JDK location
      - /c/hadoop:/opt/hadoop  # Map Hadoop installation from the host
      - /c/Users/Bek/workspace/airflow/dags/files:/opt/airflow/dags/files #Mapping local directory to a container!
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    mem_limit: 4g
    command: airflow standalone

  my-smtp:
    image: namshi/smtp
    restart: always